"""
WARPture – App Database
Pre-configured metadata for 50+ common applications on macOS and Linux.
"""

from __future__ import annotations

APP_DATABASE: list[dict[str, str]] = [
    # ── Browsers ───────────────────────────────────────────────────────────────
    {
        "id": "google-chrome",
        "name": "Google Chrome",
        "bundleId": "com.google.Chrome",
        "macPath": "/Applications/Google Chrome.app",
        "linuxExec": "google-chrome",
        "category": "browser",
    },
    {
        "id": "firefox",
        "name": "Firefox",
        "bundleId": "org.mozilla.firefox",
        "macPath": "/Applications/Firefox.app",
        "linuxExec": "firefox",
        "category": "browser",
    },
    {
        "id": "safari",
        "name": "Safari",
        "bundleId": "com.apple.Safari",
        "macPath": "/Applications/Safari.app",
        "linuxExec": "",
        "category": "browser",
    },
    {
        "id": "brave-browser",
        "name": "Brave Browser",
        "bundleId": "com.brave.Browser",
        "macPath": "/Applications/Brave Browser.app",
        "linuxExec": "brave-browser",
        "category": "browser",
    },
    {
        "id": "microsoft-edge",
        "name": "Microsoft Edge",
        "bundleId": "com.microsoft.edgemac",
        "macPath": "/Applications/Microsoft Edge.app",
        "linuxExec": "microsoft-edge",
        "category": "browser",
    },
    {
        "id": "opera",
        "name": "Opera",
        "bundleId": "com.operasoftware.Opera",
        "macPath": "/Applications/Opera.app",
        "linuxExec": "opera",
        "category": "browser",
    },
    {
        "id": "arc",
        "name": "Arc",
        "bundleId": "company.thebrowser.Browser",
        "macPath": "/Applications/Arc.app",
        "linuxExec": "",
        "category": "browser",
    },
    # ── Communication ──────────────────────────────────────────────────────────
    {
        "id": "slack",
        "name": "Slack",
        "bundleId": "com.tinyspeck.slackmacgap",
        "macPath": "/Applications/Slack.app",
        "linuxExec": "slack",
        "category": "communication",
    },
    {
        "id": "discord",
        "name": "Discord",
        "bundleId": "com.hnc.Discord",
        "macPath": "/Applications/Discord.app",
        "linuxExec": "discord",
        "category": "communication",
    },
    {
        "id": "zoom",
        "name": "Zoom",
        "bundleId": "us.zoom.xos",
        "macPath": "/Applications/zoom.us.app",
        "linuxExec": "zoom",
        "category": "communication",
    },
    {
        "id": "microsoft-teams",
        "name": "Microsoft Teams",
        "bundleId": "com.microsoft.teams2",
        "macPath": "/Applications/Microsoft Teams.app",
        "linuxExec": "teams",
        "category": "communication",
    },
    {
        "id": "whatsapp",
        "name": "WhatsApp",
        "bundleId": "net.whatsapp.WhatsApp",
        "macPath": "/Applications/WhatsApp.app",
        "linuxExec": "whatsapp-desktop",
        "category": "communication",
    },
    {
        "id": "telegram",
        "name": "Telegram",
        "bundleId": "ru.keepcoder.Telegram",
        "macPath": "/Applications/Telegram.app",
        "linuxExec": "telegram-desktop",
        "category": "communication",
    },
    {
        "id": "signal",
        "name": "Signal",
        "bundleId": "org.whispersystems.signal-desktop",
        "macPath": "/Applications/Signal.app",
        "linuxExec": "signal-desktop",
        "category": "communication",
    },
    {
        "id": "skype",
        "name": "Skype",
        "bundleId": "com.skype.skype",
        "macPath": "/Applications/Skype.app",
        "linuxExec": "skype",
        "category": "communication",
    },
    {
        "id": "facetime",
        "name": "FaceTime",
        "bundleId": "com.apple.facetime",
        "macPath": "/System/Applications/FaceTime.app",
        "linuxExec": "",
        "category": "communication",
    },
    # ── Development ────────────────────────────────────────────────────────────
    {
        "id": "vscode",
        "name": "Visual Studio Code",
        "bundleId": "com.microsoft.VSCode",
        "macPath": "/Applications/Visual Studio Code.app",
        "linuxExec": "code",
        "category": "development",
    },
    {
        "id": "cursor",
        "name": "Cursor",
        "bundleId": "com.todesktop.230313mzl4w4u92",
        "macPath": "/Applications/Cursor.app",
        "linuxExec": "cursor",
        "category": "development",
    },
    {
        "id": "jetbrains-idea",
        "name": "IntelliJ IDEA",
        "bundleId": "com.jetbrains.intellij",
        "macPath": "/Applications/IntelliJ IDEA.app",
        "linuxExec": "idea",
        "category": "development",
    },
    {
        "id": "xcode",
        "name": "Xcode",
        "bundleId": "com.apple.dt.Xcode",
        "macPath": "/Applications/Xcode.app",
        "linuxExec": "",
        "category": "development",
    },
    {
        "id": "terminal",
        "name": "Terminal",
        "bundleId": "com.apple.Terminal",
        "macPath": "/System/Applications/Utilities/Terminal.app",
        "linuxExec": "gnome-terminal",
        "category": "development",
    },
    {
        "id": "iterm2",
        "name": "iTerm2",
        "bundleId": "com.googlecode.iterm2",
        "macPath": "/Applications/iTerm.app",
        "linuxExec": "",
        "category": "development",
    },
    {
        "id": "postman",
        "name": "Postman",
        "bundleId": "com.postmanlabs.mac",
        "macPath": "/Applications/Postman.app",
        "linuxExec": "postman",
        "category": "development",
    },
    {
        "id": "docker",
        "name": "Docker Desktop",
        "bundleId": "com.docker.docker",
        "macPath": "/Applications/Docker.app",
        "linuxExec": "docker",
        "category": "development",
    },
    # ── Gaming ─────────────────────────────────────────────────────────────────
    {
        "id": "steam",
        "name": "Steam",
        "bundleId": "com.valvesoftware.steam",
        "macPath": "/Applications/Steam.app",
        "linuxExec": "steam",
        "category": "gaming",
    },
    {
        "id": "epic-games",
        "name": "Epic Games Launcher",
        "bundleId": "com.epicgames.launcher",
        "macPath": "/Applications/Epic Games Launcher.app",
        "linuxExec": "epicgameslauncher",
        "category": "gaming",
    },
    {
        "id": "battle-net",
        "name": "Battle.net",
        "bundleId": "net.battle.app",
        "macPath": "/Applications/Battle.net.app",
        "linuxExec": "battlenet",
        "category": "gaming",
    },
    {
        "id": "gog-galaxy",
        "name": "GOG Galaxy",
        "bundleId": "com.gog.galaxy",
        "macPath": "/Applications/GOG Galaxy.app",
        "linuxExec": "gogdl",
        "category": "gaming",
    },
    # ── Media ──────────────────────────────────────────────────────────────────
    {
        "id": "spotify",
        "name": "Spotify",
        "bundleId": "com.spotify.client",
        "macPath": "/Applications/Spotify.app",
        "linuxExec": "spotify",
        "category": "media",
    },
    {
        "id": "vlc",
        "name": "VLC",
        "bundleId": "org.videolan.vlc",
        "macPath": "/Applications/VLC.app",
        "linuxExec": "vlc",
        "category": "media",
    },
    {
        "id": "plex",
        "name": "Plex",
        "bundleId": "tv.plex.plexdesktop",
        "macPath": "/Applications/Plex.app",
        "linuxExec": "plex",
        "category": "media",
    },
    {
        "id": "apple-music",
        "name": "Apple Music",
        "bundleId": "com.apple.Music",
        "macPath": "/System/Applications/Music.app",
        "linuxExec": "",
        "category": "media",
    },
    {
        "id": "apple-tv",
        "name": "Apple TV",
        "bundleId": "com.apple.TV",
        "macPath": "/System/Applications/TV.app",
        "linuxExec": "",
        "category": "media",
    },
    # ── Productivity ───────────────────────────────────────────────────────────
    {
        "id": "notion",
        "name": "Notion",
        "bundleId": "notion.id",
        "macPath": "/Applications/Notion.app",
        "linuxExec": "notion-app",
        "category": "productivity",
    },
    {
        "id": "obsidian",
        "name": "Obsidian",
        "bundleId": "md.obsidian",
        "macPath": "/Applications/Obsidian.app",
        "linuxExec": "obsidian",
        "category": "productivity",
    },
    {
        "id": "microsoft-word",
        "name": "Microsoft Word",
        "bundleId": "com.microsoft.Word",
        "macPath": "/Applications/Microsoft Word.app",
        "linuxExec": "",
        "category": "productivity",
    },
    {
        "id": "microsoft-excel",
        "name": "Microsoft Excel",
        "bundleId": "com.microsoft.Excel",
        "macPath": "/Applications/Microsoft Excel.app",
        "linuxExec": "",
        "category": "productivity",
    },
    {
        "id": "libreoffice",
        "name": "LibreOffice",
        "bundleId": "org.libreoffice.script",
        "macPath": "/Applications/LibreOffice.app",
        "linuxExec": "libreoffice",
        "category": "productivity",
    },
    {
        "id": "1password",
        "name": "1Password",
        "bundleId": "com.1password.1password",
        "macPath": "/Applications/1Password 7 - Password Manager.app",
        "linuxExec": "1password",
        "category": "productivity",
    },
    {
        "id": "linear",
        "name": "Linear",
        "bundleId": "com.linear",
        "macPath": "/Applications/Linear.app",
        "linuxExec": "linear",
        "category": "productivity",
    },
    # ── Cloud Storage ──────────────────────────────────────────────────────────
    {
        "id": "dropbox",
        "name": "Dropbox",
        "bundleId": "com.getdropbox.dropbox",
        "macPath": "/Applications/Dropbox.app",
        "linuxExec": "dropbox",
        "category": "cloud",
    },
    {
        "id": "google-drive",
        "name": "Google Drive",
        "bundleId": "com.google.GoogleDrive",
        "macPath": "/Applications/Google Drive.app",
        "linuxExec": "",
        "category": "cloud",
    },
    {
        "id": "onedrive",
        "name": "OneDrive",
        "bundleId": "com.microsoft.OneDrive",
        "macPath": "/Applications/OneDrive.app",
        "linuxExec": "onedrive",
        "category": "cloud",
    },
    # ── Design ─────────────────────────────────────────────────────────────────
    {
        "id": "figma",
        "name": "Figma",
        "bundleId": "com.figma.Desktop",
        "macPath": "/Applications/Figma.app",
        "linuxExec": "figma-linux",
        "category": "design",
    },
    {
        "id": "sketch",
        "name": "Sketch",
        "bundleId": "com.bohemiancoding.sketch3",
        "macPath": "/Applications/Sketch.app",
        "linuxExec": "",
        "category": "design",
    },
    # ── Security / VPN ─────────────────────────────────────────────────────────
    {
        "id": "nordvpn",
        "name": "NordVPN",
        "bundleId": "com.nordvpn.macos",
        "macPath": "/Applications/NordVPN.app",
        "linuxExec": "nordvpn",
        "category": "security",
    },
    {
        "id": "expressvpn",
        "name": "ExpressVPN",
        "bundleId": "com.expressvpn.ExpressVPN",
        "macPath": "/Applications/ExpressVPN.app",
        "linuxExec": "expressvpn",
        "category": "security",
    },
    {
        "id": "mullvad",
        "name": "Mullvad VPN",
        "bundleId": "net.mullvad.vpn",
        "macPath": "/Applications/Mullvad VPN.app",
        "linuxExec": "mullvad",
        "category": "security",
    },
    # ── Utilities ─────────────────────────────────────────────────────────────
    {
        "id": "transmission",
        "name": "Transmission",
        "bundleId": "org.m0k.transmission",
        "macPath": "/Applications/Transmission.app",
        "linuxExec": "transmission-gtk",
        "category": "utility",
    },
    {
        "id": "qbittorrent",
        "name": "qBittorrent",
        "bundleId": "org.qbittorrent.qBittorrent",
        "macPath": "/Applications/qBittorrent.app",
        "linuxExec": "qbittorrent",
        "category": "utility",
    },
    {
        "id": "proxyman",
        "name": "Proxyman",
        "bundleId": "com.proxyman.NSProxy",
        "macPath": "/Applications/Proxyman.app",
        "linuxExec": "",
        "category": "utility",
    },
    {
        "id": "wireshark",
        "name": "Wireshark",
        "bundleId": "org.wireshark.Wireshark",
        "macPath": "/Applications/Wireshark.app",
        "linuxExec": "wireshark",
        "category": "utility",
    },
]
